### ISSUE TITLE
Should reset password requests be subject to 2FA too? 

### ISSUE THREAD

**Issue by codepotato** [michaeldzjap/Two-Factor-Authentication#7]
This awesome package latches on to the login method in Laravel and pushes users through 2FA before they can view the app. However, when you reset your password it doesn't trigger a 2FA request and I wondered, from a security standpoint, whether it should?

**Comment by michaeldzjap** [comment]
I personally would not see much added value for doing this, as after a password reset you would have to login and therefore do 2fa anyway. But it is certainly possible to build it in yourself. The `ResetsPasswords` trait doesn't have an after hook ala `AuthenticatesUsers#authenticated`, but you could use the `$redirectTo` property on the `ResetPasswordController` to redirect to a route where you could trigger the two-factor auth procedure yourself (in the same vein as is proposed for `LoginController#startTwoFactorAuthProcess` minus the logout step).

**Comment by codepotato** [comment]
Hi @michaeldzjap I might be wrong but Laravel logs you in by default when you reset your password, so it skips the 2FA step?

**Comment by michaeldzjap** [comment]
Ah yes, it actually does from the looks of it (`ResetsPasswords#resetPassword`). Even so, you could still bake in the 2fa step if you desire. You could either override the `ResetsPasswords#resetPassword` method and instead of doing `$this->guard()->login($user)` kick off the 2fa process. Or you could try the approach I suggested earlier, but make sure you logout the user before starting the 2fa process. The only thing you have to think about is what you want to have happen after you successfully finish the 2fa step after a password reset; i.e. should the user be logged in automatically after it? That's a bit tricky, but not impossible.

Either way, it is not something I can (or even if it were possible, would want to) integrate into this package, as it requires hooking into / overriding Laravel's native auth system.
